name: Pipeline

on:
  push:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Désactiver Nexus et forcer npm public
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "strict-ssl=false" >> ~/.npmrc
          npm config list

      - name: Supprimer éventuelles dépendances Nexus
        run: rm -rf node_modules package-lock.json

      - name: Installer les dépendances depuis npm public
        run: npm install --no-cache --prefer-online

      - name: Installer Lighthouse CI
        run: npm install -g @lhci/cli@0.14.x

      - name: Install http-server
        run: npm install -g http-server

      - name: Build project
        run: npm run build

      - name: Run Lighthouse CI
        run: lhci autorun

        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}